USE keiki00e;
ALTER TABLE rep_anken_test ADD ao_solution_code_raw CHAR(3);
UPDATE rep_anken_test SET ao_solution_code_raw=ao_solution_code;
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="A12" and detail_anken="3Dスキャン代行";
/*
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="2020年1Qご利用分";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="2020年4月から12月ご利用分";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度SI保守1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度SI保守2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度SI保守2月檀野";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度SI保守3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度SI保守3月檀野";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度SI保守4月ｰ6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度SI保守7月ｰ9月AO社員分";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度SI保守7月ｰ9月工藤分";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度STRAVIS技術支援1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度STRAVIS技術支援2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度STRAVIS技術支援3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度STRAVIS技術支援4月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度STRAVIS技術支援7月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度インフラ支援1月ｰ3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度インフラ支援4月ｰ6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="2021年度インフラ支援7月ｰ9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="(201906)JAREA Kintone年間ライセンス更新(再々作成)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="(201906)JAREA Krew年間ライセンス更新(再々作成)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="(再作成)JAREA様向KrewSheetライセンス(2019/03-2019/05)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="【HCM】関西ペイント様向けCi*X外部I/F開発作業2020年3月ｰ4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="【SPLA】ヤマハ様向け_HWSW RDSCAL_2019年11月-2020年2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="【新】BSFI向けOC構築・OC利用サポート";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="Acrobat Pro DC SUBS1年 Livecard";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="Asreader補修部品_モリタ製作所向け";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="BIG-IP保守（2020年4月1日-2021年3月31日）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="BIG-IP保守（2021年4月1日-2022年3月31日）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="BSFI向け　SSL証明書変更トラブル調査対応（アプリ）";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="Click Share_西松建設";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="ClickShare 御導入";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="ClickShare_CSE-200 Collabration suite";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="CTCT様向けSmartMat_初期登録費用";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="CTCT様向けSmartMat_利用料";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ES事業部向けトレーニング環境_ﾈｯﾄﾜｰｸ関連(FortiCloud)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="FB様向けファイルサーバーJP1ライセンス保守20191201-20201130";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="HP_Workstation_奥田精工向け（2台目）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="IBMパスポート・アドバンテージ";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="IJTT様向けHP Z6 G4 Workstation";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ISID BIG-IP製品(リース)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ISID BIG-IP保守(リース)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ISID RedHat AnsibleTower 5年";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ISID RHEL 5年";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ISID 仮想基盤更改　Senjuサブスクリプション(11ヶ月）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ISID 仮想基盤更改　Senjuサブスクリプション(11ヶ月）ﾙｰﾙ･SEN Con･SEN Ope";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ISID様_社内検証用_MS RDS UserCAL日本語版SA更新(6User)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ISID様検証用_MS RDS UserCAL日本語版SA更新(6User)※非占有型";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="JAREA様向Kintoneライセンス(2018年度追加)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="JAREA様向Kintoneライセンス(2019年度4月追加)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="JAREA様向けkintoneライセンス（2018年度12月追加分）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="JAREA様向けkintoneライセンス（2018年度）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="JAREA様向けkintoneライセンス追加アカガバ_スタンダード（2本）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="kintone スタンダードコース 年額 アカデミック・ガバメント版";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="kintone セキュアアクセス 年額";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="kintoneアカウント(アカガバ3本)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="kintoneアカウント（年額アカガバ20本）";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_ｴｺﾌﾟﾛｼﾞｪｸﾄ_年間契約(1806-1905）";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_ﾎﾜｲﾄﾌｧｸﾄﾘｰ_年間契約(1808-1907）";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_ﾗｲｽﾞ_年間契約(1811-1910)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_ﾗｲｽﾞ_年間契約(1903-1910)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通_実績精算契約(1901)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通(1902)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通(1903)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通(1904)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通(1905)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通(1906)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通(1907)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通(1908)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通(1909)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="KMB_電通ﾃｯｸ_6ヶ月契約(1904-1909）";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="KTX殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="LIXIL様向けRPAによるSimufact自動化検証_2021年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="LIXIL様向けRPA検証支援";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="MW更改向け_Senju/ENｻﾌﾞｽｸﾘﾌﾟｼｮﾝﾗｲｾﾝｽ ﾊﾟｯｹｰｼﾞｿﾌﾄｳｪｱ_Senju Enterprise Navigator_2018";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="MW更改向け_Senju/OCｻﾌﾞｽｸﾘﾌﾟｼｮﾝ(1)ﾊﾟｯｹｰｼﾞｿﾌﾄｳｪｱ_Senju DevOperation Conductor_SJ11308";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="MW更改向け_Senju/OCｻﾌﾞｽｸﾘﾌﾟｼｮﾝ(2)ﾊﾟｯｹｰｼﾞｿﾌﾄｳｪｱ_Senju DevOperation Conductor_2018";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="MW更改向け_Senju/OCｻﾌﾞｽｸﾘﾌﾟｼｮﾝ(3)ﾊﾟｯｹｰｼﾞｿﾌﾄｳｪｱ_Senju DevOperation Conductor_2018";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="NFCカードリーダーおよびIoTゲートウェイデバイス";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ＮＩＳＳＨＡ様向けＰＣログ対応2020年5月ｰ7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="OutSystems開発およびJIRAサポート支援_2021年7-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID＿セミアクティブ_TDM_保守（1904-2003）";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID_セミアクティブ入退館_ソフトウェア";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID_セミアクティブ入退館_ハードウェア";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID_セミアクティブ入退館_機器設置作業費";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID_セミアクティブ入退館_作業";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID-セミアク　TDM　タグの修理　2019/10";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFIDタグ";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFIDリーダー";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID入退館ソリューション 保守_2104-2203";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID入退館ソリューション　名古屋新オフィス施工費（追加分）";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="RFID物品管理_有償PoC_月島機械_201906";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_aru_TSK_AWS運用・管理作業21年1月-22年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="roconie_aru_TSK_AWS利用料(サーバホスト)202010-202109";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="roconie_aru_TSK_ライセンス/サーバー費用";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_aru_TSK_資材管理_RFIDタグ";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_aru_TSK_資材管理_作業費";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="roconie_aru_TSK_製品ｽﾃｰﾀｽ管理ｼｽﾃﾑの年間保守";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_TDM_RFIDハードウェア一式";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_TDM_RFIDハードウェア一式　修正版";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_TDM_システム設定_プロ管費（施工費以外の作業）";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_TDM_施工費";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_TDモバイル_タグ修理費20/07";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="Roconie_TDモバイル_タグ追加購入";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_TDモバイル_マクロ改修";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_TDモバイル_入退館保守費_2004-2103";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_TSK_追加機能開発";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_モノタロウ_PoC費用";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_月島機械_2020追加機能実装";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="Roconie_月島機械_モノ";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Roconie_月島機械_現場実績レポートシステム利用料";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Ronconie*aru_EXCELソフトウェア";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="Ronconie*aru_EXCEL導入費用";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="SCCM用基盤拡張製品（リース）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="SCCM用基盤拡張保守";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="Share point導入作業（社内サーバ老朽化対応）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="SIC様向けUiPathインフラ老朽化更新作業（5-9月作業分）";
UPDATE rep_anken_test SET ao_solution_code_raw="310" where ao_solution_code="702" and detail_anken="SISW向けNXサポート業務_2019年4-9月_高木";
UPDATE rep_anken_test SET ao_solution_code_raw="310" where ao_solution_code="702" and detail_anken="SISW向けNXサポート業務_2019年10月-2020年03月_高木";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="smartmat_CTCテクノロジー_利用料20年7月-21年6月";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="TM_BearTail 6ヶ月利用分(1903-1908)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="TM_BearTail_年間契約(1909-2008)";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="TM_KBS_年間契約（1909-2008）";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="TOTO様向けRoconie*aruトライアル費用一式";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A11" and detail_anken="touch-mee システム利用費用";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A11" and detail_anken="touch-mee システム利用費用_5月追加分";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A11" and detail_anken="touch-mee 初期費用";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A11" and detail_anken="touch-mee 初期費用_5月追加分";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A11" and detail_anken="touch-mee_kbs_2年目更新分";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A11" and detail_anken="touch-mee_kbs_3年目更新分";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="touch-mee_kbs_履歴レポート改修";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A10" and detail_anken="touch-mee_カルビー株式会社（初期費用）";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A11" and detail_anken="touch-mee_カルビー株式会社（利用料）";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A10" and detail_anken="touch-mee_初期費用";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A11" and detail_anken="touch-mee_年間利用料金";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="touch-mee_年間利用料金（12月追加分）";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="UACJ殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アイカ工業株式会社_UiPath支援_2019年11-12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アイカ工業様向け_UiPathトレーニング_2021年3月-5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アイカ工業様向け_Uipathロボット改修支援_2021年4月-5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アイカ工業様向け_UiPath要件定義作業_2021年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アイメタルテクノロジー様向けHP Z240 Workstation";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="アクリル製NFCシート";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アシックス様向け_UiPathトレーニング_2019年7月-8月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="アスパーク殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アライドテレシス様向けJP1ライセンス";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アライドテレシス様向けJP1初年度保守";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="アライドテレシス様向けJP1保守更新（2020年5月-2021年5月）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="イオンディライト_Uipath導入支援2021年3月-4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="イオンディライト_UiPath導入支援_2020年11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="いすゞ自動車向けUiPath基礎教育";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="ウェブサイト改修提案";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エア・ウォーター_UiPath導入推進支援_2019年4月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エア・ウォーター_UiPath導入推進支援_2019年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エア・ウォーター_UiPath導入推進支援_2019年8月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エア・ウォーター_UiPath導入推進支援_2019年8月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エア・ウォーター_UiPath導入推進支援_2019年9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エスペック様向け勤怠項目60進変更対応2020年8月ｰ10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン_UiPath導入支援_2020年1月-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン_UiPath導入推進支援_2019年4月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン_UiPath導入推進支援_2019年10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン_UiPath導入推進支援_2019年11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン_UiPath導入推進支援_2019年12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン_UiPath導入推進支援_2020年4月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン様向け_UiPath導入推進支援_2019年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン様向け_UiPath導入推進支援_2019年8月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="エディオン様向け_UiPath導入推進支援_2019年9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2020年5月ｰ6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2020年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2020年8月ｰ9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2020年10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2020年11月12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2021年1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2021年2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2021年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2021年4月5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2021年6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネカ様向けＣｉ＊Ｘ導入支援作業2021年7月ｰ8月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="カネボウ労働組合　西日本支部様　ウイルスチェック機能 拡張・延長 パック 5年";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="キューピータマゴ様　ClickShare　CSE-200（Std）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援9月導入追加対応";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2020年1月ｰ3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2020年4月ｰ6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2020年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2020年8月ｰ9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2020年10月ｰ12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2021年1月ｰ2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2021年3月ｰ4月(EIS)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2021年3月ｰ4月(西日本）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2021年5月ｰ6月(EIS)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2021年5月ｰ6月(西日本）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2021年7月ｰ9月アドオン(EIS)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2021年7月ｰ9月アドオン(西日本）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援2021年7月ｰ9月導入(西日本）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X導入支援(9社目追加対応)2020年9月ｰ12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クボタ様向けCi*X保守2021年3月ｰ6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="クラシエHD様_ｱﾝｹｰﾄｻｰﾊﾞ用ﾊﾞｯｸｱｯﾌﾟﾂｰﾙ ﾗｲｾﾝｽ(1年)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="コニカミノルタ様向け_第四次拡大 CAD on VDI Nimbleストレージ保守（1年）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="コニカミノルタ様向け_第四次拡大 CAD on VDI NVIDAIﾗｲｾﾝｽ保守（5年）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="コニカミノルタ様向け_第四次拡大 Citrixﾗｲｾﾝｽ保守（1年）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="コンチネンタルAM向けRPA電話サポート";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="ｺﾝﾁﾈﾝﾀﾙAM殿向　販売支援手数料(6月)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ｺﾝﾁﾈﾝﾀﾙAM殿向販売支援手数料(UiPathｻﾎﾟｰﾄ)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ｺﾝﾁﾈﾝﾀﾙAM殿向販売支援手数料(UiPathライセンス)";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="ｺﾝﾁﾈﾝﾀﾙｵｰﾄﾓｰﾃｨﾌﾞ_販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="サーバ・保守料金";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="サンスタッフ殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="サンスタッフ殿向け販売支援手数料（初年度保守）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="スズキ向け_PMO業務サポート_2019年5月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="スズキ向け_PMO業務サポート_2019年7月-8月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="スズキ向け_PMO業務サポート_2019年12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="セキュアアクセス（月額3本）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="セキュアアクセス（年額3本）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="セキュリティチェックリスト作成支援";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="303" and detail_anken="セミナー支援（8月、9月）（SS)";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="303" and detail_anken="セミナー支援（10月ー12月）（SS)";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="ダイキン工業様向けインフラ支援（レスポンス検証）_2021年7-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ダイトロン_UiPath導入推進支援_2019年11月-12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ダイトロン_UiPath導入推進支援_2020年1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ダイトロン株式会社_UiPath導入支援_2020年10月-12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="デルタ工業様向け UipathクラウドOC導入支援_2021年6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="トールエクスプレスジャパン_UiPathトレーニング_2019年12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="トールエクスプレスジャパン_UiPath導入推進支援_2019年10月-11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="トールエクスプレスジャパン_UiPath導入推進支援_2019年11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="トールエクスプレスジャパン様向け_UiPath業務支援_2020年2月-4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="トールエクスプレスジャパン様向け_UiPath業務支援_2020年10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="トヨタ紡織株式会社_UiPathサポート_2019年5月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="トヨタ紡織様向け　AVR for GP4　保守更新";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="ノートPC_ヤマハ発動機向け";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="ハードウェア";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="バイエル薬品_UiPath導入推進支援_2019年10月-12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="バッファロー様向け_UiPathクラウドOC導入支援_2021年4月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="パナソニックAP_HeartCore導入推進支援_2019年11月-12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPathトレーニング_2019年1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath改修支援_2019年9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath改修支援_2019年10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath改修支援_2019年12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath改修支援_2020年2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath改修支援_2020年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath改修支援_2020年4月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath改修支援_2020年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath技術支援_2020年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath導入推進支援_2019年12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFA&HRプロパートナーズ_UiPath導入推進支援_2020年1月-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFAHRプロパートナーズ 様向け UiPathロボット改修支援_2021年7月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFAHRプロパートナーズ_UiPath導入推進支援_2020年1月-2020年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFAHRプロパートナーズ(RPA推進部)_UiPath導入推進支援_2020年4月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パナソニックFAHRプロパートナーズ(RPA推進部)_UiPath導入推進支援_2020年7月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="パナソニック株式会社_SCRYU Tetra Windows移植作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パラマウントケアサービス様向けUiPathロボット開発";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パラマウントベッド向けOC構築・ロボットUR化対応";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="パラマウントベッド様向けRPAリモート保守サービス（2021年7-12月）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様_HWSW_ADサーバリプレース（HW・SW）_CAL";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様_HWSW_FIND2.0 ph3 SVFレンタルライセンス";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様向け_HWSW_JP1追加ライセンス保守（20181201-20191130）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様向け_HWSW_JP1追加ライセンス保守（20191201-20201130）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様向け_HWSW_リネンシステムCitrix保守更新（20201201-20211130）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様向け_HWSW_リネンシステムSW保守（20191201-20201130）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様向けFIND2.0 ph4_MS RDS SAL　GWサーバ";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様向けFIND2.0 ph4_MS RDS SAL　XenAPP";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="フランスベッド様向けFIND2.0 ph4_MS RDS SAL　XenAPP（10月利用発注分訂正）";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="702" and detail_anken="マツダ様　振動騒音及び剛性の開発支援業務";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="702" and detail_anken="マツダ様　振動騒音及び剛性の開発支援業務_2020年4月-2021年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="702" and detail_anken="マツダ様　振動騒音及び剛性の開発支援業務_2021年4月-2022年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="みなと銀行様向けPOSITIVEデータ移行ツール対応作業（テスト・本番切り替え）1月ｰ3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="みなと銀行様向けPOSITIVEデータ移行ツール対応作業（テスト）11月ｰ12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="みなと銀行様向けPOSITIVEデータ移行ツール対応作業（開発）8月ｰ9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="みなと銀行様向けPOSITIVEデータ移行ツール対応作業（開発）10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="みなと銀行様向けPOSITIVEデータ移行ツール対応作業（外部設計）6月ｰ7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="みなと銀行様向けPOSITIVEデータ移行対応作業1月-3月(谷崎)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="みなと銀行様向けPOSITIVEデータ移行対応作業（外部設計）4月ｰ5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="メイテツコム様向けOrchestrator構築支援_2020年6月-7月";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A11" and detail_anken="モリタ製作所様向けAsReader本体ならびに付属品 一式";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A11" and detail_anken="モリタ製作所様向けAsZaiライセンス_1月開始分";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A11" and detail_anken="モリタ製作所様向けAsZaiライセンス_2月開始分";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A11" and detail_anken="モリタ製作所様向けAsZaiライセンス_3月開始分";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A11" and detail_anken="モリタ製作所様向けAsZaiライセンス_12月開始分";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A11" and detail_anken="モリタ製作所様向けAsZai年間ライセンス";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ユニー様向け　アドオン改修対応";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="ユニキャリア様向け_Net Scaler製品保守　20161101-20211031";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="303" and detail_anken="りそなカード様オペレーションコンソール交換作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="運用保守_2020年1Ｑ分";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="運用保守_2020年4月_2021年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="運用保守_2021年4月_2022年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="奥田精工殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="奥田精工殿向け販売支援手数料（2台目）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="奥田精工様向けWindows10ボリュームライセンス";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="株式会社メニコン様向けUiPathサポート_2019年10月-12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="株式会社東洋シート_UiPathサポート_2019年10月-11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="株式会社菱友システム技術_UiPathトレーニング_2020年1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="関西ペイント様向け　在宅勤務手当および扶養手当支給対応6月7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="関西ペイント様向け　年休取得日数集計の自動連結対応9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="関西ペイント様向けCi*X導入2020年4月ｰ6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="関西ペイント様向け追加案件(ゾーンアップ対応)作業　8月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="紀伊産業_処方設計支援システム_追加開発";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="京セラドキュメントソリューションズ株式会社様向け 開発保守2019年1-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="熊野精工殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A11" and detail_anken="栗本鐵工所_Roconie_ソフトウェア";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="栗本鐵工所_Roconie_導入作業（準委任部分）";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="栗本鐵工所_Roconie_導入作業（請負部分）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="光ビジネスアクセスNEXT_初期費用";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="光ビジネスアクセスNEXT_利用費用";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="光精工殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="310" where ao_solution_code="302" and detail_anken="広SL1部マツダ保守サポート業務_2019年1-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="阪大微生物病研究会 様向け Uipath推進支援_2021年4月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="阪大微生物病研究会様向け Uipath OC構築作業_2021年4月-5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="阪大微生物病研究会様向けUipath推進支援_2021年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="堺化学工業様向け UiPath導入推進支援_2019年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="堺化学工業様向け UiPath導入推進支援_2019年4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="堺化学工業様向け UiPath導入推進支援_2019年5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="三浦工業_UiPathトレーニング_2019年12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="三菱コントロールパネル_UiPath導入推進支援業務_2020年1月-2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="三菱ロジスネクスト様向け_RDS SAL（2019年1-12月）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="三菱電機_UiPath教育支援_2020年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="三菱電機_UiPath導入推進支援_2019年12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="三菱電機_UiPath導入推進支援_2020年1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="三菱電機エンジニアリング_UiPathサポート_2019年3月-6月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="山口精機工業殿向販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="山田養蜂場ECサイト構築におけるPMO業務支援";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="山田養蜂場ECサイト構築におけるPMO業務支援（8-10月）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="山田養蜂場ECサイト構築におけるPMO業務支援（11-3月）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="燦ホールディングス株式会社_UiPath教育支援_2020年11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="燦ホールディングス株式会社_UiPath導入支援_2020年11月-12月";
UPDATE rep_anken_test SET ao_solution_code_raw="A02" where ao_solution_code="A12" and detail_anken="磁性シート分";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="鹿児島銀行様向けバージョンアップ作業4月ｰ6月（佐藤、杉山）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="鹿児島銀行様向けバージョンアップ作業7月ｰ9月（佐藤、杉山）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="鹿児島銀行様向けバージョンアップ作業10月（佐藤）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="鹿児島銀行様向けバージョンアップ作業11月（佐藤）";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="鹿児島銀行様向けバージョンアップ作業12月（佐藤）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="住公システム元号改元テスト作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="初期費用（環境調査）及び稼働支援";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="松永製作所殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="神戸製鋼所_UiPath(OC)環境構築・導入推進支援_2019年2月-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2019年1-3月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2019年4-6月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2019年10-12月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2020年1-3月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2020年4-6月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2020年7-9月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2020年10-12月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2021年1-3月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2021年4月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2021年5-6月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_2021年7-9月分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="生産準備系コンサルティング業務_22019年7-9月分";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="製造事業部向けトレーニング環境_ﾈｯﾄﾜｰｸ関連(FortiCloudログ管理オプションライセンス（1年）)";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="302" and detail_anken="西日本技術部様向けCAD_CAE_PLMサポート業務_2019年1-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="西尾レントオール_UiPathトレーニング_2019年9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業(IEP)向け新人事制度対応 2021年7月ｰ9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE　7月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="319" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE　アドオン保守対応 2020年10月ｰ12月";
UPDATE rep_anken_test SET ao_solution_code_raw="319" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE　アドオン保守対応 2021年3月ｰ4月";
UPDATE rep_anken_test SET ao_solution_code_raw="319" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE　アドオン保守対応 2021年5月ｰ7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE　新人事制度変更対応（給与計算）8月ｰ9月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE　目標管理（評価・自己申告・昇降格）対応 2020年8月ｰ10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE　夜勤代番退勤時のタイムレコーダー打刻時間対応 2020年9月ｰ10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE　要件定義作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE（退職金機能追加対応10月）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE（谷、西中）8月ｰ9月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE（谷、西中）10月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE(浮穴、國澤)8月ｰ9月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE(浮穴、國澤)10月ｰ12月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE(浮穴)1月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE(浮穴)2月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE(國澤)1月作業";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向けPOSITIVE外部I/F対応作業12月-2月（谷）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向け就労WFデータチェック作業1月-2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="石原産業向け就労WFデータチェック追加作業3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="大阪建築技術協会_UiPath導入支援_2020年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="大阪建築技術協会_UiPath導入支援_2020年4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="大成様向けUiPathサポート_2021年3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="大創産業様向け　新勤怠システム連携対応4月-5月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="中部合成樹脂工業殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="椿本チェイン様向け　アドバイザー追加開発対応3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="東映アニメーション株式会社向け請求支払業務効率化にかかわる作業";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="東海興業殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="東海合金工業殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="東京インキ様_HW/SW_MS RDS CAL(5User)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="東京インキ様_HW/SW_MS RDS CAL(5User)追加分";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="東京インキ様_Oracle Database StandardEdition2 Named User Plus（10）年間保守";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="東京インキ様向け 検証環境用 MS RDS User CAL L/SA（5User）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="東京インキ様向け 検証環境用 MS RDS User CAL L/SA（5User）追加分";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="東陽殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="導入プロジェクト_19年12月末";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="導入作業費";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="奈良市_UiPath導入支援_2019年10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="奈良市_UiPath導入支援_2019年11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="奈良市_UiPath導入支援_2019年12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント　再雇用_契約社員の制度変更対応10月ｰ11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント　人事データ整備作業8月ｰ9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント　定年再雇用支給条件追加対応11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント（ＡＳペイント）様向けガソリン単価連携対応2020年9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント（ＡＳペイント）様向け休業補償手当対応2020年10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント（ＡＳペイント）様向け給与就業導入作業2020年10月ｰ12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント（ＡＳペイント）様向け給与就業要件定義作業2月ｰ4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント（ＡＳペイント）様向け給与就実装ーテスト作業5月ｰ9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント様向け　ASP遡及月変更対応開発2月3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント様向け　海外給与計算式変更作業1月2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント様向け　時間外単価変更業2月3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント様向け　職務給追加対応作業1月2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日本ペイント様向け　新基幹職人事制度改正作業1月2月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船_UiPath、VBA開発支援_2021年6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船_UiPath、VBA開発支援_2021年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船_UiPath、VBA開発支援_2021年8月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船_UiPathトレーニング_2019年10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船_UiPathトレーニング_2019年11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船_UiPath導入支援_2021年6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船_UiPath導入支援_2021年7月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船_UiPath導入支援_2021年8月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_Orchestrator構築後支援_2020年4月-5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_Orchestrator構築作業_2020年5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath、VBA開発支援_2020年8月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath、VBA開発支援_2020年10月-11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath、VBA開発支援_2021年1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath、VBA開発支援_2021年2月-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath、VBA開発支援_2021年4月-5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath開発支援_2020年10月-11月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath開発支援_2020年11月-12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath導入支援_2020年2月-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath導入支援_2020年2月-4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath導入支援_2020年4月-5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath導入支援_2020年6月-9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath導入支援_2021年1月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath導入支援_2021年2月-3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="日立造船株式会社_UiPath導入支援_2021年4月-5月";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A10" and detail_anken="白板家　JM-1500";
UPDATE rep_anken_test SET ao_solution_code_raw="A01" where ao_solution_code="A12" and detail_anken="白板家_CTCT_販売";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="菱友システム技術_UiPathトレーニング_2021年5月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="富士生命様向けRPA開発体制強化支援2019年1月ｰ3月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="富士生命様向けRPA開発体制強化支援2019年4月ｰ6月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="富士生命様向けRPA開発体制強化支援2019年7月ｰ9月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="富士生命様向けRPA開発体制強化支援2019年10月ｰ12月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="富士通ﾌﾟﾛｷｭｱﾒﾝﾄｻｰﾋﾞｽ様向けZertoライセンス(6ヵ月)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="富士物流株式会社_UiPathトレーニング_2019年10月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="富士物流株式会社様向け_UiPathトレーニング_2020年2月";
UPDATE rep_anken_test SET ao_solution_code_raw="320" where ao_solution_code="320" and detail_anken="扶桑精工殿向け販売支援手数料";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="兵庫医科大学様向け_UiPath StudioXトレーニング(基礎編)";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="兵庫医科大学様向け_UiPathトライアル期間QAサポート(オフサイト)対応_2020年6月-8月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="平和堂様向けSmartHR対応ファイル連携(追加）作業2020.12-2021.03";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="平和堂様向けSmartHR対応ファイル連携作業2020.10-2021.03";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="平和堂様向け賃金改定対応作業3月ｰ4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="A12" and detail_anken="返金対応";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="豊田自動織機様向けUNITYライセンス";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="豊田自動織機様向けUNITYライセンス（更新）";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="堀場エステック_UiPath Orchestrator構築作業_2021年3月-4月";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="本田技研工業株式会社向けAIOCRPoC";
UPDATE rep_anken_test SET ao_solution_code_raw="999" where ao_solution_code="320" and detail_anken="矢崎総業向けUNITYライセンス";
